title: "Utkarsh Mangal"
description: "Assistant Research Professor â€” Yonsei University College of Dentistry"
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
# IMPORTANT for project pages:
url: "https://utkmangal.github.io"
baseurl: "/utkmangal"
plugins:
  - jekyll-feed
  - jekyll-seo-tag