title: "Utkarsh Mangal"
description: "Assistant Research Professor â€” Yonsei University College of Dentistry"
theme: jekyll-theme-minimal

# Required for project sites
url: "https://utkmangal.github.io"
baseurl: "/utkmangal"

# Assets
favicon: "/utkmangal/assets/favicon.ico"
show_downloads: false
markdown: kramdown
plugins: []
